import { z } from "zod"

import type { SparePartSearchCriteria } from "@/lib/validations/spare-part-search-url"

/**
 * The public spare-parts catalogue's search parameters.
 *
 * ── Why parsing is forgiving rather than strict ───────────────────────
 * Everything here arrives in a query string, which is user-editable,
 * bookmarked, pasted into WhatsApp, and rewritten by link previewers. A
 * malformed value is an ordinary event, not an exceptional one, so each field
 * falls back to "not filtered" rather than throwing: `?page=banana` shows page
 * one, `?category=nonsense` shows every part.
 *
 * That is *not* the same as trusting the input. Every value that survives is
 * length-bounded and type-checked before it reaches Prisma, and the query
 * layer parameterises it — so a category slug containing a quote is a value
 * that matches nothing, never syntax.
 *
 * ── The two ways a customer narrows the catalogue ─────────────────────
 * `category` is the rail of chips at the top of the page. It carries the
 * category's *slug*, not its id: a slug is stable, readable in a shared link,
 * and survives a database restore into a fresh environment where ids differ.
 * Absent means "All", which is the default — the page opens showing
 * everything.
 *
 * `q` is the search box beneath it: one field matched against the part name,
 * the manufacturer's number and our own reference at once, so someone holding
 * an old part can type what is stamped on it without first deciding which
 * kind of number it is.
 *
 * The two combine rather than compete — a category chip and a search term are
 * ANDed by the query layer.
 */

/**
 * Upper bound on the category slug.
 *
 * The rail only ever emits slugs that exist, so a legitimate value is short.
 * The cap is aimed at a hand-edited URL carrying kilobytes into a query.
 */
const CATEGORY_SLUG_MAX_LENGTH = 60

/**
 * A category slug as it arrives from the URL.
 *
 * Empty and whitespace-only collapse to `undefined`, which is what the "All"
 * chip means — and what a GET form submits for an unselected control.
 *
 * The character class is deliberately narrow. Slugs are generated by
 * `slugifyFragment`, so anything outside `[a-z0-9-]` was not produced by this
 * application; refusing it here means the value never reaches a query at all.
 */
const categoryFilter = z
  .string()
  .trim()
  .toLowerCase()
  .max(CATEGORY_SLUG_MAX_LENGTH)
  .regex(/^[a-z0-9-]*$/)
  .transform((value) => (value.length === 0 ? undefined : value))
  .optional()
  .catch(undefined)

/**
 * Upper bound on the free-text search box.
 *
 * Long enough for "toyota harrier front brake pads", short enough that a
 * pasted paragraph never reaches the database. Over the limit the term is
 * dropped entirely (`.catch`), which shows the unfiltered catalogue rather
 * than an error page.
 */
const SEARCH_TERM_MAX_LENGTH = 80

/**
 * The free-text query.
 *
 * Whitespace is trimmed *and* collapsed, so "brake   pads" and "brake pads"
 * are one URL rather than two addresses for one result set.
 */
const searchTerm = z
  .string()
  .trim()
  .max(SEARCH_TERM_MAX_LENGTH)
  .transform((value) => value.replace(/\s+/g, " "))
  .transform((value) => (value.length === 0 ? undefined : value))
  .optional()
  .catch(undefined)

/**
 * The page number.
 *
 * Separate from the filters below because it is not one: it does not narrow
 * the result set, and every filter change resets it.
 */
const pageFilter = z
  .union([z.string(), z.number()])
  .transform((value) => {
    const parsed = Number(typeof value === "number" ? value : value.trim())

    return Number.isInteger(parsed) && parsed > 0 ? parsed : 1
  })
  .catch(1)
  .default(1)

export const sparePartSearchSchema = z.object({
  q: searchTerm,
  category: categoryFilter,
  page: pageFilter,
})

export type SparePartSearchParams = z.infer<typeof sparePartSearchSchema>

/**
 * The criteria type and URL builders live in `spare-part-search-url.ts`,
 * which does not import Zod, so Client Components can use them without
 * shipping Zod to the browser. Re-exported here so server code keeps one
 * import.
 */
export {
  buildPartCatalogueQuery,
  hasActivePartSearch,
  partCatalogueHref,
  type SparePartSearchCriteria,
} from "@/lib/validations/spare-part-search-url"

/**
 * Compile-time proof that the hand-written `SparePartSearchCriteria` is
 * exactly what the schema produces, so the two cannot drift apart.
 */
type SchemaCriteria = Omit<SparePartSearchParams, "page">
type SameShape<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false
const criteriaMatchesSchema: SameShape<SchemaCriteria, SparePartSearchCriteria> = true
void criteriaMatchesSchema

/**
 * Parses a Next.js `searchParams` object.
 *
 * A value arrives as `string | string[] | undefined`: a URL may legally repeat
 * a key, and `?category=brakes&category=engine` is not a filter the rail can
 * represent. The first occurrence wins, which matches what a browser submits
 * from a form and what the links in `spare-part-search-url.ts` build.
 */
export function parseSparePartSearchParams(
  params: Record<string, string | string[] | undefined>
): SparePartSearchParams {
  const first = (value: string | string[] | undefined) =>
    Array.isArray(value) ? value[0] : value

  return sparePartSearchSchema.parse({
    q: first(params.q),
    category: first(params.category),
    page: first(params.page) ?? 1,
  })
}
